version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pokemon_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: pokemon_web
    ports:
      - "5001:5000"
    environment:
      # sceret key 생성 python -c 'import secrets; print(secrets.token_hex())'
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=1
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: